# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotabelementimage',
            name='file_location',
            field=models.FileField(upload_to='tours/images/'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='current_site_marker',
            field=models.FileField(blank=True, help_text='Suggested image size: 32px x 32px', null=True, upload_to='tours/map_markers/'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='next_site_marker',
            field=models.FileField(blank=True, help_text='Suggested image size: 32px x 32px', null=True, upload_to='tours/map_markers/'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='site_unvisited_marker',
            field=models.FileField(blank=True, help_text='Suggested image size: 32px x 32px', null=True, upload_to='tours/map_markers/'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='site_visited_marker',
            field=models.FileField(blank=True, help_text='Suggested image size: 32px x 32px', null=True, upload_to='tours/map_markers/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='file_location',
            field=models.FileField(upload_to='tours/images/'),
        ),
    ]
