# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_userfeedback_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_slug',
            field=models.SlugField(help_text="A unique identifier used to differentiate this site's url from any other."),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_slug',
            field=models.SlugField(help_text="A unique identifier used to differentiate this tour's url from any other.", unique=True),
        ),
    ]
