# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20160401_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpage',
            name='feedback_request_checkpoint',
            field=models.PositiveSmallIntegerField(default=3, help_text='The number of sites that are visited before a request for feedback is made.'),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='In decimal degree format. Supports six decimal places.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='In decimal degree format. Supports six decimal places.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='map_default_zoom',
            field=models.PositiveSmallIntegerField(help_text='The zoom amount of the map when page is first loaded.'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='map_lower_bound',
            field=models.OneToOneField(help_text='The bottom left of the map. Be generous with how much space is provided.', on_delete=django.db.models.deletion.CASCADE, related_name='map_lower_bound', to='tours.MapLocation'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='map_max_zoom',
            field=models.PositiveSmallIntegerField(help_text='How far the map can be zoomed in', verbose_name='Map maximum zoom'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='map_min_zoom',
            field=models.PositiveSmallIntegerField(help_text='How far the map can be zoomed out', verbose_name='Map minimum zoom'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='map_upper_bound',
            field=models.OneToOneField(help_text='The top right of the map. Be generous with how much space is provided.', on_delete=django.db.models.deletion.CASCADE, related_name='map_upper_bound', to='tours.MapLocation'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(help_text='Short description given under image slider.'),
        ),
        migrations.AlterField(
            model_name='site',
            name='simple_directions',
            field=models.TextField(help_text='Directions given when traveling to the site. Should be applicable to all incoming directions to support all tour orders.'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='file_location',
            field=models.FileField(help_text='Insure all images are the same size for best results on the image slider.', upload_to='tours/images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='site_nickname',
            field=models.CharField(help_text='Another name for the sites on the tour. Used for generating text for buttons.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='travel_method',
            field=models.CharField(choices=[('DRIVING', 'DRIVING'), ('WALKING', 'WALKING'), ('BICYCLING', 'BICYCLING'), ('TRANSIT', 'TRANSIT')], help_text='Determines how the Google Maps API will give best path.', max_length=9),
        ),
    ]
