# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20160401_0906'),
        ('tours', '0011_remove_site_site_type'),
    ]

    operations = [
    ]
