# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20160413_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutelement',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title and Description.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title.'),
        ),
        migrations.AddField(
            model_name='feedbackpage',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title and Description.'),
        ),
        migrations.AddField(
            model_name='infotab',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Description.'),
        ),
        migrations.AddField(
            model_name='infotabelement',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title and Description.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title and Description.'),
        ),
        migrations.AddField(
            model_name='site',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title, Simple Directions, and Description.'),
        ),
        migrations.AddField(
            model_name='thankyoupage',
            name='serve_as_html',
            field=models.BooleanField(default=False, help_text='Enables full html use in text fields. Affects: Title and Description.'),
        ),
    ]
