# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20160413_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_css',
            field=models.FileField(blank=True, null=True, upload_to='tours/css/'),
        ),
    ]
