# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20160505_0533'),
        ('tours', '0015_auto_20160506_0405'),
    ]

    operations = [
    ]
